### ISSUE TITLE
npm ERR! code E404 npm ERR! 

### ISSUE THREAD

**Issue by lod61** [liriliri/eruda-vue#1]
```
npm ERR! code E404 npm ERR! 
404 Not Found: eruda-vue@latest
```
是不是vue得这个不管用？node 里面找了下也没有source。

**Comment by surunzi** [comment]
开了坑，还没有时间填。。。

**Comment by vintprox** [comment]
Oh, how unfortunate that Vue inspection is off. By the way keep up the good work :) Eruda are great embeddable devtools!

**Comment by surunzi** [comment]
已支持。
